server:
  port: 8081
  servlet:
    context-path: /qf-hospital
spring:
  thymeleaf:
    cache: false
  datasource:
    name: localhost_3306
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/hospitaldb?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000


mybatis:
  type-aliases-package: com.xlq.hospital.model
  mapper-locations:
  - classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
ftp:
  address: 120.78.143.104
  port: 21
  username: ftpuser
  password: 123456
  baseUrl: http://120.78.143.104:8082
  basePath: /home/myFtp
logging:
  level:
    com.xlq.hospital.dao: debug